#!/bin/bash

if [ ! -d ".venv" ]; then
    echo creating python venv...
    python3 -m venv .venv
    source .venv/bin/activate
    echo installing dependencies...
    pip3 install -r requirements.txt
fi

source .venv/bin/activate
python3 main.py "$@"
deactivate